export enum ERouteList {
  SplashScreen = "SplashScreen",
  Start = "Start",
  SignUp = "SignUp",
  LogIn = "LogIn",
  ForgetPass = "ForgetPass",
  Courses = "Courses",
  CourseTab = "CourseTab",
  CourseDetails = "CourseDetails",
  Cart = "Cart",
  Favorites = "Favorites",
  Drawer = "Drawer",
  DrawerTab = "DrawerTab",
  Settings = "Settings",
  EditProfile = "EditProfile",
}
